from collections.abc import Callable
from typing import Literal, Protocol

from shared.domain import entities


class GlobalHotkeyProvider(Protocol):
    def start(self, callback: Callable[[str], None]) -> None: ...
    def stop(self) -> None: ...


class TrackSearcher(Protocol):
    async def search_tracks(
        self, query: str, limit: int = 10
    ) -> list[entities.Track] | None: ...

    async def search_albums(
        self, query: str, limit: int = 10
    ) -> list[entities.Album] | None: ...

    async def search_artists(
        self, query: str, limit: int = 10
    ) -> list[entities.Artist] | None: ...


class TrackStreamer(Protocol):
    async def get_stream_url(self, track_id: int) -> str: ...


class TrackProvider(Protocol):
    async def get_playlist_tracks(
        self, playlist_id: str
    ) -> entities.Playlist | None: ...

    async def get_album_tracks(self, album_id: str) -> entities.Album | None: ...

    async def get_track(self, track_id: int) -> entities.Track | None: ...

    async def get_artist_details(self, artist_id: str) -> entities.Artist | None: ...


class PlaybackController(Protocol):
    async def play(self, url: str) -> None: ...

    async def pause(self) -> None: ...

    async def resume(self) -> None: ...


class VolumeController(Protocol):
    async def set_volume(self, volume_level: int) -> None: ...


class PlaybackMonitor(Protocol):
    def get_position_ms(self) -> int: ...

    def set_position_ms(self, pos_ms: int) -> None: ...

    def is_playing(self) -> bool: ...


class QueueManager(Protocol):
    async def add_track(
        self, track: entities.Track, position: Literal["next", "end"] = "end"
    ) -> None: ...

    async def set_queue(self, queue: entities.TrackQueue) -> None: ...

    async def next_track(self) -> entities.Track | None: ...

    async def prev_track(self) -> entities.Track | None: ...

    async def remove_track(self, node_id: str) -> None: ...

    async def clear(self) -> None: ...

    async def get_current(self) -> entities.Track | None: ...

    async def get_all(self) -> list[entities.Track] | None: ...

    async def set_repeat_mode(self, mode: str) -> None: ...
